project:
  type: website
  output-dir: docs   

website:
  title: "Violencia de Género"
  navbar:
    logo: "tvr.jpg"
    background: purple
    right:
      - text: "Trabajo individual"
        href: blog.qmd
      - icon: github
        href: https://github.com/<Paumars3>
      - icon: twitter
        href: https://twitter.com/<tu-usuario-twitter>
      - icon: envelope
        url: "mailto:<tu-mail@alumni.uv.es>"
    page-footer: 
      background: "purple" 
      left: "© 2022 Paula Martínez" #--
      center: "Hecho con [Quarto](https://quarto.org)"
   
format:
  html:
    theme: flatly           #- https://quarto.org/docs/output-formats/html-themes.html
    highlight-style: a11y   #-
    css: my_styles.css      #- si queréis añadir cosas
    page-layout: full
    toc: true
    code-copy: true
    code-overflow: wrap    
    code-fold: show
    code-line-numbers: true
    
lang: es

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999)
